Add decode/encode functions to JsonFileHelper
keboola/php-component pull request #52
Opened 2018-10-20 23:01 UTC by Actimel

2018-10-20 23:03 UTC, Actimel commented
Zaroven jsem prejmenoval i tu tridu. Kdyz to umi i obycejny `encode`/`decode`, tak by bylo zvlastni aby se jmenovala `JsonFileHelper`

2018-10-22 08:19 UTC, tomasfejfar requested changes

2018-10-22 08:19 UTC, tomasfejfar commented on src/JsonHelper.php
>      public static function read(string $filePath): array
readFile

2018-10-22 08:19 UTC, tomasfejfar commented on src/JsonHelper.php
>      public static function write(string $filePath, array $data, bool $formatted = true): void
writeFile

2018-10-22 08:19 UTC, tomasfejfar commented on src/JsonHelper.php
>      public static function read(string $filePath): array
readFile

2018-10-22 08:19 UTC, tomasfejfar commented on tests/JsonHelperTest.php
> +class JsonHelperTest extends TestCase
Chybí testy na nově přidané metody.

2018-10-23 08:34 UTC, tomasfejfar requested changes
Kromě prohozených metod v testech LGTM

2018-10-23 08:34 UTC, tomasfejfar commented on tests/JsonHelperTest.php
> +    public function testEncodeFormattedSuccessfully(): void
prohozené

2018-10-23 08:34 UTC, tomasfejfar commented on tests/JsonHelperTest.php
> +    public function testEncodeFormattedSuccessfully(): void
v názvu metody formated/not formated

2018-10-23 08:41 UTC, tomasfejfar approved these changes

2018-10-23 14:20 UTC, merged

2018-12-25 16:12 UTC, tomasfejfar commented
Haha, koukám, že jsem tady celkem posral review :) 

https://github.com/keboola/php-component/blob/master/tests/JsonHelperTest.php#L151

Test tady je a testuje skutečné chování. Jenže ono by se to mělo chovat jinak! Opravuju v rámci #53 

https://github.com/keboola/php-component/blob/master/src/JsonHelper.php#L51